name: Build MiniPass

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libboost-all-dev libgtest-dev sqlite3 libsqlite3-dev cmake g++

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build

      - name: Run tests
        run: cd build && ctest --output-on-failure

      - name: Upload built binary
        uses: actions/upload-artifact@v4
        with:
          name: minipass-binary
          path: build/src/minipass
