name: Build MiniPass

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install cmake build-essential libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev \
              mesa-common-dev libxcb-cursor0 qt6-base-dev qt6-base-dev-tools qt6-tools-dev qt6-tools-dev-tools \
              qt6ct qt6-multimedia-dev libgtest-dev libxkbcommon-dev libboost-all-dev
          cd /usr/src/gtest && sudo cmake . && sudo make && sudo mv lib* /usr/lib/ && cd -

      # Set up the build environment and configure CMake
      - name: Configure CMake
        run: |
          export QT_QPA_PLATFORM=xcb
          export PATH="/usr/lib/qt6/bin:$PATH"
          QT_PATH="/usr/lib/x86_64-linux-gnu/cmake/Qt6"
          QT_LIB_PATH="/usr/lib/qt6/libexec"
          
          echo "Cleaning directories..."
          rm -rf "$GITHUB_WORKSPACE/bin" "$GITHUB_WORKSPACE/build" "$GITHUB_WORKSPACE/out"
          
          echo "Creating build/ directory..."
          mkdir -p "$GITHUB_WORKSPACE/build"
          cd "$GITHUB_WORKSPACE/build"
          
          echo "Running CMake configuration..."
          cmake -G "Unix Makefiles" -DCMAKE_PREFIX_PATH="$QT_PATH" "$GITHUB_WORKSPACE"
      # Build the project
      - name: Build the project
        run: |
          cd "$GITHUB_WORKSPACE/build"
          make VERBOSE=1

      # Copy binaries
      - name: Copy build artifacts
        run: |
          if [ -f "$GITHUB_WORKSPACE/build/minipass" ]; then
            mkdir -p "$GITHUB_WORKSPACE/bin"
            cp "$GITHUB_WORKSPACE/build/minipass" "$GITHUB_WORKSPACE/bin"
            echo "Success: minipass build was successful."
          else
            echo "Error: minipass build was not successful."
            exit 1
          fi

      # Run tests if they exist
      - name: Run tests
        run: |
          cd "$GITHUB_WORKSPACE/build"
          ctest --output-on-failure
