name: Release MiniPass

on:
  push:
    tags:
      - 'v*'
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install cmake build-essential libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev \
              mesa-common-dev libxcb-cursor0 qt6-base-dev qt6-base-dev-tools qt6-tools-dev qt6-tools-dev-tools \
              qt6ct qt6-multimedia-dev libgtest-dev libxkbcommon-dev jq
          cd /usr/src/gtest && sudo cmake . && sudo make && sudo mv lib* /usr/lib/ && cd -

      - name: Configure CMake
        run: |
          export QT_QPA_PLATFORM=xcb
          export PATH="/usr/lib/qt6/bin:$PATH"
          QT_PATH="/usr/lib/x86_64-linux-gnu/cmake/Qt6"
          QT_LIB_PATH="/usr/lib/qt6/libexec"
          rm -rf "$GITHUB_WORKSPACE/bin" "$GITHUB_WORKSPACE/build" "$GITHUB_WORKSPACE/out"
          mkdir -p "$GITHUB_WORKSPACE/build"
          cd "$GITHUB_WORKSPACE/build"
          cmake -G "Unix Makefiles" -DCMAKE_PREFIX_PATH="$QT_PATH" "$GITHUB_WORKSPACE"
          "$QT_LIB_PATH/uic" "$GITHUB_WORKSPACE/src/minipass.ui" -o "$GITHUB_WORKSPACE/src/ui_minipass.h"

      - name: Build the project
        run: |
          cd "$GITHUB_WORKSPACE/build"
          cmake --build . --config Release

      - name: Get stable version and description from version.json
        run: |
            version=$(jq -r '.stable' version.json)
            description=$(jq -r --arg version "$version" '.changelog[] | select(.version == $version) | .description' version.json)
            echo "version=$version" >> $GITHUB_ENV
            echo "description=$description" >> $GITHUB_ENV
        shell: /usr/bin/bash -e {0}
  
      - name: Set up Git for pushing tags
        run: |
              git config --global user.name "github-actions"
              git config --global user.email "github-actions@github.com"
  
      - name: Create Git Tag
        run: |
          version=$(jq -r '.stable' version.json)

          if git rev-parse "v$version" >/dev/null 2>&1; then
            echo "Tag v$version already exists. Skipping tag creation."
          else
            git tag "v$version"
            git push origin "v$version"
            echo "version=$version" >> $GITHUB_ENV
          fi
  
      - name: Copy build artifacts
        run: |
            if [ -f "$GITHUB_WORKSPACE/build/src/minipass" ]; then
              mkdir -p "$GITHUB_WORKSPACE/release"
              cp "$GITHUB_WORKSPACE/build/src/minipass" "$GITHUB_WORKSPACE/release"
              tar -czvf minipass.tar.gz -C release minipass
            else
              echo "Error: minipass build was not successful."
              exit 1
            fi
  
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.version }}"
          name: "minipass v${{ env.version }}"
          body: "Release description for minipass v${{ env.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
